common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/wit/imu"

preprocess:
    lidar_type: 1                # Livox series LiDAR
    feature_extract_en: false
    scan_line: 6
    blind: 1

initialization:
    cut_frame_num: 5 # must be positive integer
    orig_odom_freq: 10
    mean_acc_norm: 9.805 # 1: for livox built-in IMU
    online_refine_time: 20.0
    data_accum_length: 500
    Rot_LI_cov: [ 0.00005, 0.00005, 0.00005 ]
    Trans_LI_cov: [ 0.00001, 0.00001, 0.00001 ]

mapping:
    filter_size_surf: 0.05
    filter_size_map: 0.15
    gyr_cov: 50
    acc_cov: 2
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    det_range:     260.0

color_mapping:
    use_color: true
    K_camera: [766.38136,   0     , 628.1358 ,
           0     , 720.66146, 348.08063,
           0     ,   0     ,   1.     ]
    D_camera: [-0.327005, 0.077308, 0.000458, 0.002563, 0.000000]
    time_offset_lidar_to_camera: 0                # ms         # lidar to camera

    extrinsic_T: [0.10319 ,0.69730 , 0.34090]          # lidar to camera
    extrinsic_R: [-0.07069,  0.99665,   -0.04124,
                  -0.20849,  0.02567,   0.97769,
                  0.97547 ,  0.07771,   0.20597]

# -0.07069  -0.20849  0.97547   -0.17987  
# 0.99665   0.02567   0.07771   -0.14724  
# -0.04124  0.97769   0.20597   -0.74770 


publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
